DROP TABLE IF EXISTS posts;

CREATE TABLE IF NOT EXISTS posts (
    id SERIAL PRIMARY KEY, -- 👈 BIGSERIAL から SERIAL に変更しました！
    content VARCHAR(256) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);